pipeline:
  name: iacsetup
  identifier: iacsetup
  projectIdentifier: Terraformsetup
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ica
        identifier: ica
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: iac_service
          environment:
            environmentRef: terraformbase
            deployToAll: false
            infrastructureDefinitions:
              - identifier: nedef
          execution:
            steps:
              - step:
                  type: ShellScriptProvision
                  name: ShellScriptProvision_1
                  identifier: ShellScriptProvision_1
                  spec:
                    source:
                      type: Inline
                      spec:
                        script: |-
                          #!/bin/bash

                          # fail on any error
                          set -eu

                          # install yum-config-manager to manage your repositories
                          sudo yum install -y yum-utils

                          # use yum-config-manager to add the official HashiCorp Linux repository
                          sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

                          # install terraform
                          sudo yum -y install terraform

                          # verify terraform is installed
                          terraform --version

                          # Clone the Terraform repository
                          https://github.com/rsaifi12/ua_terraform.git
                          cd ua_terraform

                          # Initialize Terraform (only run once)
                          terraform init

                          # Navigate to the directory where your Terraform configurations are stored
                          #cd /path/to/your/terraform/config

                          # Create an execution plan
                          terraform plan -out=tfplan

                          # Apply the execution plan (with auto-approval)
                          terraform apply -auto-approve tfplan
                    environmentVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: PipelineRollback
        when:
          pipelineStatus: All
  properties:
    ci:
      codebase:
        connectorRef: gitconnector
        repoName: ua_terraform
        build: <+input>
