pipeline:
  name: iacsetup
  identifier: iacsetup
  projectIdentifier: Terraformsetup
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ica
        identifier: ica
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: iac_service
          environment:
            environmentRef: terraformbase
            deployToAll: false
            infrastructureDefinitions:
              - identifier: runterra
          execution:
            steps:
              - step:
                  type: TerraformApply
                  name: TerraformApply_1
                  identifier: TerraformApply_1
                  spec:
                    provisionerIdentifier: aws
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            spec:
                              connectorRef: awsconnector
                              bucketName: harnessbucket12
                              region: us-east-1
                              folderPath: hanrssf/
                            type: S3
                  timeout: 10m
                  when:
                    stageStatus: Success
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Authentication
                          - Connectivity
                        action:
                          type: Ignore
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: PipelineRollback
        when:
          pipelineStatus: All
  properties:
    ci:
      codebase:
        connectorRef: gitconnector
        repoName: ua_terraform
        build: <+input>
